/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BoardHistoryRouteImport } from './routes/board-history'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MathosDoticsRouteImport } from './routes/mathos[.]ics'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThroughTheYearsRouteImport } from './routes/through-the-years'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicHooksSyncFormEmailsRouteImport } from './routes/api.public.hooks.sync-form-emails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardHistoryRoute = BoardHistoryRouteImport.update({
  id: '/board-history',
  path: '/board-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MathosDoticsRoute = MathosDoticsRouteImport.update({
  id: '/mathos.ics',
  path: '/mathos.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThroughTheYearsRoute = ThroughTheYearsRouteImport.update({
  id: '/through-the-years',
  path: '/through-the-years',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncFormEmailsRoute =
  ApiPublicHooksSyncFormEmailsRouteImport.update({
    id: '/api/public/hooks/sync-form-emails',
    path: '/api/public/hooks/sync-form-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/board-history': typeof BoardHistoryRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/mathos.ics': typeof MathosDoticsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/through-the-years': typeof ThroughTheYearsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/sync-form-emails': typeof ApiPublicHooksSyncFormEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/board-history': typeof BoardHistoryRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/mathos.ics': typeof MathosDoticsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/through-the-years': typeof ThroughTheYearsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/sync-form-emails': typeof ApiPublicHooksSyncFormEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/board-history': typeof BoardHistoryRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/mathos.ics': typeof MathosDoticsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/through-the-years': typeof ThroughTheYearsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/sync-form-emails': typeof ApiPublicHooksSyncFormEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/board-history'
    | '/details'
    | '/faq'
    | '/mathos.ics'
    | '/register'
    | '/sitemap.xml'
    | '/through-the-years'
    | '/admin/login'
    | '/admin/'
    | '/api/public/hooks/sync-form-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/board-history'
    | '/details'
    | '/faq'
    | '/mathos.ics'
    | '/register'
    | '/sitemap.xml'
    | '/through-the-years'
    | '/admin/login'
    | '/admin'
    | '/api/public/hooks/sync-form-emails'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/board-history'
    | '/details'
    | '/faq'
    | '/mathos.ics'
    | '/register'
    | '/sitemap.xml'
    | '/through-the-years'
    | '/admin/login'
    | '/admin/'
    | '/api/public/hooks/sync-form-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  BoardHistoryRoute: typeof BoardHistoryRoute
  DetailsRoute: typeof DetailsRoute
  FaqRoute: typeof FaqRoute
  MathosDoticsRoute: typeof MathosDoticsRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThroughTheYearsRoute: typeof ThroughTheYearsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicHooksSyncFormEmailsRoute: typeof ApiPublicHooksSyncFormEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-history': {
      id: '/board-history'
      path: '/board-history'
      fullPath: '/board-history'
      preLoaderRoute: typeof BoardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mathos.ics': {
      id: '/mathos.ics'
      path: '/mathos.ics'
      fullPath: '/mathos.ics'
      preLoaderRoute: typeof MathosDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/through-the-years': {
      id: '/through-the-years'
      path: '/through-the-years'
      fullPath: '/through-the-years'
      preLoaderRoute: typeof ThroughTheYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-form-emails': {
      id: '/api/public/hooks/sync-form-emails'
      path: '/api/public/hooks/sync-form-emails'
      fullPath: '/api/public/hooks/sync-form-emails'
      preLoaderRoute: typeof ApiPublicHooksSyncFormEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  BoardHistoryRoute: BoardHistoryRoute,
  DetailsRoute: DetailsRoute,
  FaqRoute: FaqRoute,
  MathosDoticsRoute: MathosDoticsRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThroughTheYearsRoute: ThroughTheYearsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicHooksSyncFormEmailsRoute: ApiPublicHooksSyncFormEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
